version: '3'

services:
  gestionaleluca-db-1:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestionale
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - gestionaleluca-db-1
    volumes:
      - .:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: gestionaleluca-db-1
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - gestionaleluca-db-1

volumes:
  db_data: