# Generated by Django 5.0.1 on 2024-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('indirizzo_sede', models.CharField(blank=True, max_length=255)),
                ('n_civico_sede', models.CharField(blank=True, max_length=10)),
                ('citta_sede', models.CharField(blank=True, max_length=255)),
                ('provincia_sede', models.CharField(blank=True, max_length=2)),
                ('cap_sede', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
