# Generated by Django 5.0.1 on 2024-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornitore', '0001_initial'),
        ('Pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='pagamento',
            field=models.ManyToManyField(blank=True, choices=[], to='Pagamento.pagamento', verbose_name='Metodi pagamento possibili'),
        ),
    ]
