# Generated by Django 5.0.1 on 2024-01-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornitore', '0002_fornitore_pagamento'),
        ('Pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='pagamento',
            field=models.ManyToManyField(blank=True, choices=[(1, 'TEST PAGAMENTO 1'), (2, 'TEST PAGAMENTO 2'), (3, 'TEST PAGAMENTO 3')], to='Pagamento.pagamento', verbose_name='Metodi pagamento possibili'),
        ),
    ]
